CREATE TABLE IF NOT EXISTS cats(
  id SERIAL PRIMARY KEY,
  name VARCHAR (255) NOT NULL,
  race VARCHAR (255) NOT NULL,
  sex VARCHAR (10) NOT NULL,
  age_in_month INT,
  description VARCHAR (255) NOT NULL,
  image_urls VARCHAR[] NOT NULL,
  user_id INT REFERENCES users(id) NOT NULL,
  has_matched BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ
);